DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT (ID INT PRIMARY KEY AUTO_INCREMENT, username VARCHAR, PASSWORD VARCHAR);

INSERT INTO ACCOUNT (username, PASSWORD) VALUES ('seungwoo1', '000');
INSERT INTO ACCOUNT (username, PASSWORD) VALUES ('seungwoo2', '000');
INSERT INTO ACCOUNT (username, PASSWORD) VALUES ('seungwoo3', '000');
INSERT INTO ACCOUNT (username, PASSWORD) VALUES ('seungwoo4', '000');